version: "3.1"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sumdb
      MYSQL_USER: sumdb
      MYSQL_PASSWORD: letmein
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --silent --execute "SHOW DATABASES;"
      interval: 3s
      timeout: 2s
      retries: 5

  clone:
    build: 
      context: ../../..
      dockerfile: ./clone/cmd/sumdbclone/Dockerfile
    command: [
      "--alsologtostderr",
      "--v=2",
      "--mysql_uri=sumdb:letmein@tcp(db:3306)/sumdb",
      "--write_batch_size=1024",
      "--workers=4",
    ]
    restart: always
    depends_on:
      db:
        condition: service_healthy
