version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /binary_transparency/firmware/cmd/ft_personality
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /binary_transparency/firmware/cmd/ftmapserver
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /clone/cmd/ctclone
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /clone/cmd/ctverify
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /clone/cmd/sumdbclone
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /integration
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /serverless/deploy/github/distributor/combine_witness_signatures
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: gomod
  directory: /serverless/deploy/github/distributor/combine_witness_signatures
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /serverless/deploy/github/distributor/update_logs_index
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: gomod
  directory: /serverless/deploy/github/distributor/update_logs_index
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /serverless/deploy/github/log/leaf_validator
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /serverless/deploy/github/log/sequence_and_integrate
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: gomod
  directory: /serverless/experimental/gcp-log/gcs_uploader
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: gomod
  directory: /serverless/experimental/gcp-log
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /sumdbaudit/docker/mirror
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directory: /sumdbaudit/docker/witness
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"
