version: 2
updates:
- package-ecosystem: gomod
  directories:
    - /
    - /serverless/deploy/github/distributor/combine_witness_signatures
    - /serverless/deploy/github/distributor/update_logs_index
    - /serverless/experimental/gcp-log
    - /serverless/experimental/gcp-log/gcs_uploader
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directories:
    - /binary_transparency/firmware/cmd/ft_personality
    - /binary_transparency/firmware/cmd/ftmapserver
    - /clone/cmd/ctclone
    - /clone/cmd/ctverify
    - /clone/cmd/sumdbclone
    - /integration
    - /serverless/deploy/github/distributor/combine_witness_signatures
    - /serverless/deploy/github/distributor/update_logs_index
    - /serverless/deploy/github/log/leaf_validator
    - /serverless/deploy/github/log/sequence_and_integrate
  schedule:
    interval: weekly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

