version: 2
updates:
- package-ecosystem: gomod
  directories:
    - /
  schedule:
    interval: monthly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

- package-ecosystem: docker
  directories:
    - /binary_transparency/firmware/cmd/ft_personality
    - /binary_transparency/firmware/cmd/ftmapserver
    - /clone/cmd/ctclone
    - /clone/cmd/ctverify
    - /clone/cmd/sumdbclone
    - /integration
  schedule:
    interval: monthly
  groups:
    all-deps:
      applies-to: version-updates
      patterns:
        - "*"

