version: '3.2'
services:
  witness:
    image: gcr.io/trillian-opensource-ci/omniwitness-monolith:${WITNESS_VERSION}
    volumes:
        - type: volume
          source: data
          target: /data
          volume:
            nocopy: true
    command:
      - "--listen=:8100"
      - "--db_file=/data/witness.sqlite"
      - "--private_key=${WITNESS_PRIVATE_KEY}"
      - "--public_key=${WITNESS_PUBLIC_KEY}"
      - "--gh_user=${GIT_USERNAME}"
      - "--gh_email=${GIT_EMAIL}"
      - "--gh_token=${GITHUB_AUTH_TOKEN}"
      - "--logtostderr"
      - "--v=2"
    restart: always
    ports:
      - "8100:8100"
volumes:
  data:
