sequenceDiagram

    participant flash as Device Flash
    participant bootloader as Device bootloader

    rect rgba(80,80,80,0.1)
        note right of flash: Cold boot
        activate bootloader
        bootloader ->>+ flash: Read ProofBundle
        flash -->>- bootloader: ProofBundle
        bootloader -->> bootloader: Verify ProofBundle
        rect rgba(255, 0, 0, 0.2)
            opt ProofBundle invalid
                bootloader -->> bootloader: HaltAndReportError
            end
        end
         rect rgba(255, 0, 0, 0.2)
            opt Signature Mismatch
                bootloader -->> bootloader: HaltAndReportError
            end
        end
        rect rgba(255, 0, 0, 0.2)
            opt Inclusion Mismatch
                bootloader -->> bootloader: HaltAndReportError
            end
        end
        bootloader ->>+ flash: Measure firmware
        flash -->>- bootloader: Firmware Measurement
        rect rgba(255, 0, 0, 0.2)
            opt Measurement invalid
                bootloader -->> bootloader: HaltAndReportError
            end
        end
        bootloader ->> bootloader: Chain to firmware
        deactivate bootloader
    end