sequenceDiagram
    participant vendor as Firmware Vendor
    participant log as Log Operator
    participant update as Update Client
    participant flash as Device Flash
 
    opt Notify clients
        activate vendor
        vendor --X update: New update available
        deactivate vendor
    end

    rect rgba(80,80,80,0.1)
        note right of log: Client update
        activate update
        update ->> update: Trigger Update
        update ->>+ flash: Fetch previous STH
        flash -->>- update: STH_old
        update ->>+ log: GetConsistencyProofRequest{STH_update, STH_old}
        log -->>- update: GetConsistencyProofResponse
        update ->> update: Verify
            rect rgba(80,80,80,0.1)
            note right of update: 1.Verify the signature on Fw Manifest <br> 2.Compute STH from STH_old and consist<br> proof received from above <br> 3. Compute STH from Fw Manifest Hash &<br> Inclusion proof from bundle <br> 4. Verification succeeds when STH from 2 & 3 <br>matches STH_update from bundle
            end
        activate update
        rect rgba(0,192,0,0.3)
            alt Verification successful
              update ->>+ flash: Write Firmware + Proof Bundle
              flash -->>- update: Write OK
            end
        end
    end
