sequenceDiagram
    participant vendor as Firmware Vendor
    participant log as Log Operator
    participant update as Update Client
    participant flash as Device Flash


    opt Notify clients
        activate vendor
        vendor --X update: New update available
        deactivate vendor
    end

    rect rgba(80,80,80,0.1)
        note right of log: Client update
        activate update
        update ->> update: Trigger Update

        update ->> update: Verify
            rect rgba(80,80,80,0.1)
                alt Verification Flow
        note right of update: <br> 1.Verify the signature on FW Manifest <br> 2.Compute STH from Fw Manifest Hash<br> & Inclusion proof from bundle <br>3.Verification succeeds when computed <br>STH matches STH_update from bundle
                end
            end

        activate update
        rect rgba(0,192,0,0.3)
            alt Verification successful
                update ->>+ flash: Write Firmware + Proof Bundle
                flash -->>- update: Write OK
            end
        end
    end