# This compose script brings up a standalone Pixel BT witness that
# polls the log every 5 minutes, and exposes the cosigned checkpoints
# via a REST API on port 8123.
# When running, the witnessed checkpoint will be at:
# http://localhost:8123/witness/v0/logs/d0a1f19e973cd5cc3d4f26446ea418d33faefffb43ea1e3eadfe133287f71ff8/checkpoint
#
# See https://go.dev/play/p/ZKrAbQovsZK for an example of generating
# the key material for the witness signing.
#
# This compose script is not intended for configuring a witness
# that can witness other logs. See the `/witness/golang/` directory
# in this repo for greater flexibility.

version: '3.2'
services:
  witness:
    image: gcr.io/trillian-opensource-ci/witness:latest
    volumes:
        - type: volume
          source: data
          target: /data
          volume:
            nocopy: true
        - type: bind
          source: ./standalone.conf
          target: /witness-config
          read_only: true
    command:
      - "--listen=:8123"
      - "--db_file=/data/witness.sqlite"
      - "--private_key=${WITNESS_PRIVATE_KEY}"
      - "--config_file=/witness-config/pixelwitness.yaml"
      - "--logtostderr"
    restart: always
    ports:
      - "8123:8123"
  feeder:
    depends_on:
      - witness
    image: gcr.io/trillian-opensource-ci/pixel-bt-feeder:latest
    command:
      - "--config_file=/feeder-config/feeder.yaml"
      - "--interval=5m"
      - "--alsologtostderr"
      - "--v=1"
    restart: always
    volumes:
      - type: bind
        source: ./standalone.conf
        target: /feeder-config
        read_only: true
volumes:
  data:
