// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

/*
Package configpb is a generated protocol buffer package.

It is generated from these files:
	config.proto

It has these top-level messages:
	HubMultiConfig
	HubConfigSet
	HubConfig
	TrackedSource
*/
package configpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import keyspb "github.com/google/trillian/crypto/keyspb"
import sigpb "github.com/google/trillian/crypto/sigpb"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HubMultiConfig wraps up a collection of HubConfig messages with a
// corresponding map of backend specifications so that the configuration
// can be parsed as a single proto.
type HubMultiConfig struct {
	// The set of hubs that will use the backends below. All the protos in this
	// HubConfigSet must set a valid hub_backend_name for the config to be usable.
	HubConfig []*HubConfig `protobuf:"bytes,1,rep,name=hub_config,json=hubConfig" json:"hub_config,omitempty"`
	// The collection of backends that this configuration will use to send requests to.
	// The key for the map is the backend name (referenced by HubConfig.backend_name)
	// and the corresponding value defines the RPC endpoint that clients should use to
	// send requests to this hub backend. These values should be in the same format as
	// rpcBackendFlag in the hub_server main and must not be an empty string.
	HubBackends map[string]string `protobuf:"bytes,2,rep,name=hub_backends,json=hubBackends" json:"hub_backends,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HubMultiConfig) Reset()                    { *m = HubMultiConfig{} }
func (m *HubMultiConfig) String() string            { return proto.CompactTextString(m) }
func (*HubMultiConfig) ProtoMessage()               {}
func (*HubMultiConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HubMultiConfig) GetHubConfig() []*HubConfig {
	if m != nil {
		return m.HubConfig
	}
	return nil
}

func (m *HubMultiConfig) GetHubBackends() map[string]string {
	if m != nil {
		return m.HubBackends
	}
	return nil
}

// HubConfigSet holds a set of hub configurations as a single message to allow
// configuration of a hub using a default backend.
type HubConfigSet struct {
	Config []*HubConfig `protobuf:"bytes,1,rep,name=config" json:"config,omitempty"`
}

func (m *HubConfigSet) Reset()                    { *m = HubConfigSet{} }
func (m *HubConfigSet) String() string            { return proto.CompactTextString(m) }
func (*HubConfigSet) ProtoMessage()               {}
func (*HubConfigSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HubConfigSet) GetConfig() []*HubConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// HubConfig describes the configuration options for a hub instance.
type HubConfig struct {
	LogId      int64                `protobuf:"varint,1,opt,name=log_id,json=logId" json:"log_id,omitempty"`
	Prefix     string               `protobuf:"bytes,2,opt,name=prefix" json:"prefix,omitempty"`
	Source     []*TrackedSource     `protobuf:"bytes,3,rep,name=source" json:"source,omitempty"`
	PrivateKey *google_protobuf.Any `protobuf:"bytes,4,opt,name=private_key,json=privateKey" json:"private_key,omitempty"`
	// The public key is included for the convenience of test tools (and obviously
	// should match the private key above); it is not used by the hub.
	PublicKey *keyspb.PublicKey `protobuf:"bytes,5,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	// backend_name (if set) indicates which backend serves this hub.  When enclosed in
	// a HubMultiConfig the name must be one of the keys for the hub_backends map.
	BackendName string `protobuf:"bytes,6,opt,name=backend_name,json=backendName" json:"backend_name,omitempty"`
}

func (m *HubConfig) Reset()                    { *m = HubConfig{} }
func (m *HubConfig) String() string            { return proto.CompactTextString(m) }
func (*HubConfig) ProtoMessage()               {}
func (*HubConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HubConfig) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *HubConfig) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *HubConfig) GetSource() []*TrackedSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *HubConfig) GetPrivateKey() *google_protobuf.Any {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *HubConfig) GetPublicKey() *keyspb.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *HubConfig) GetBackendName() string {
	if m != nil {
		return m.BackendName
	}
	return ""
}

// TrackedSource describes a source that this gossip hub will accept signed blobs from.
type TrackedSource struct {
	Name          string                              `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id            string                              `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	PublicKey     *keyspb.PublicKey                   `protobuf:"bytes,3,opt,name=public_key,json=publicKey" json:"public_key,omitempty"`
	HashAlgorithm sigpb.DigitallySigned_HashAlgorithm `protobuf:"varint,4,opt,name=hash_algorithm,json=hashAlgorithm,enum=sigpb.DigitallySigned_HashAlgorithm" json:"hash_algorithm,omitempty"`
}

func (m *TrackedSource) Reset()                    { *m = TrackedSource{} }
func (m *TrackedSource) String() string            { return proto.CompactTextString(m) }
func (*TrackedSource) ProtoMessage()               {}
func (*TrackedSource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TrackedSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TrackedSource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TrackedSource) GetPublicKey() *keyspb.PublicKey {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *TrackedSource) GetHashAlgorithm() sigpb.DigitallySigned_HashAlgorithm {
	if m != nil {
		return m.HashAlgorithm
	}
	return sigpb.DigitallySigned_NONE
}

func init() {
	proto.RegisterType((*HubMultiConfig)(nil), "configpb.HubMultiConfig")
	proto.RegisterType((*HubConfigSet)(nil), "configpb.HubConfigSet")
	proto.RegisterType((*HubConfig)(nil), "configpb.HubConfig")
	proto.RegisterType((*TrackedSource)(nil), "configpb.TrackedSource")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 474 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0x92, 0x6d, 0x44, 0x27, 0xdd, 0x6a, 0x31, 0x0b, 0x84, 0x9e, 0x4a, 0xc5, 0xa1, 0x08,
	0xc9, 0x41, 0x5d, 0xad, 0x84, 0x40, 0x42, 0x5a, 0x3e, 0xa4, 0xa2, 0x02, 0x42, 0x29, 0xf7, 0xc8,
	0x4e, 0xdc, 0xc4, 0xaa, 0x1b, 0x47, 0x89, 0xb3, 0x22, 0x7f, 0x8b, 0x9f, 0xc2, 0x9f, 0xe1, 0x8a,
	0x62, 0x3b, 0xfb, 0x75, 0x59, 0x2e, 0xc9, 0xbc, 0x99, 0xf7, 0x3c, 0x6f, 0x3c, 0x86, 0x49, 0x2a,
	0xcb, 0x1d, 0xcf, 0x71, 0x55, 0x4b, 0x25, 0xd1, 0x03, 0x83, 0x2a, 0x3a, 0x3b, 0xcf, 0xb9, 0x2a,
	0x5a, 0x8a, 0x53, 0x79, 0x88, 0x72, 0x29, 0x73, 0xc1, 0x22, 0x55, 0x73, 0x21, 0x38, 0x29, 0xa3,
	0xb4, 0xee, 0x2a, 0x25, 0xa3, 0x3d, 0xeb, 0x9a, 0x8a, 0xda, 0x9f, 0x39, 0x60, 0x76, 0x76, 0xbf,
	0xac, 0xe9, 0xcf, 0x37, 0x5f, 0x2b, 0x7a, 0x66, 0x99, 0x1a, 0xd1, 0x76, 0x17, 0x91, 0xb2, 0x33,
	0xa5, 0xc5, 0x1f, 0x07, 0xa6, 0xeb, 0x96, 0x7e, 0x6b, 0x85, 0xe2, 0x1f, 0xb5, 0x37, 0xb4, 0x02,
	0x28, 0x5a, 0x9a, 0x18, 0xa7, 0xa1, 0x33, 0xf7, 0x96, 0xc1, 0xea, 0x11, 0x1e, 0x8c, 0xe3, 0x75,
	0x4b, 0x0d, 0x31, 0x1e, 0x17, 0x43, 0x88, 0xbe, 0xc2, 0xa4, 0xd7, 0x50, 0x92, 0xee, 0x59, 0x99,
	0x35, 0xa1, 0xab, 0x55, 0x2f, 0x6f, 0xa9, 0x6e, 0xf4, 0xe8, 0xe1, 0x07, 0xcb, 0xfd, 0x5c, 0xaa,
	0xba, 0x8b, 0x83, 0xe2, 0x3a, 0x33, 0x7b, 0x0f, 0x27, 0x77, 0x09, 0xe8, 0x04, 0xbc, 0x3d, 0xeb,
	0x42, 0x67, 0xee, 0x2c, 0xc7, 0x71, 0x1f, 0xa2, 0x53, 0x18, 0x5d, 0x12, 0xd1, 0xb2, 0xd0, 0xd5,
	0x39, 0x03, 0xde, 0xba, 0x6f, 0x9c, 0xc5, 0x3b, 0x98, 0x5c, 0xb9, 0xdc, 0x32, 0x85, 0x5e, 0x81,
	0x7f, 0xff, 0x34, 0x96, 0xb2, 0xf8, 0xeb, 0xc0, 0xf8, 0x2a, 0x8b, 0x1e, 0x83, 0x2f, 0x64, 0x9e,
	0xf0, 0x4c, 0x77, 0xf6, 0xe2, 0x91, 0x90, 0xf9, 0x97, 0x0c, 0x3d, 0x01, 0xbf, 0xaa, 0xd9, 0x8e,
	0xff, 0xb2, 0xcd, 0x2d, 0x42, 0x11, 0xf8, 0x8d, 0x6c, 0xeb, 0x94, 0x85, 0x9e, 0xee, 0xf4, 0xf4,
	0xba, 0xd3, 0xcf, 0xba, 0x9f, 0x27, 0xdb, 0xea, 0x72, 0x6c, 0x69, 0xe8, 0x1c, 0x82, 0xaa, 0xe6,
	0x97, 0x44, 0xb1, 0xa4, 0x1f, 0xef, 0x68, 0xee, 0x2c, 0x83, 0xd5, 0x29, 0x36, 0x0b, 0xc3, 0xc3,
	0xc2, 0xf0, 0x45, 0xd9, 0xc5, 0x60, 0x89, 0x1b, 0xd6, 0xa1, 0xd7, 0x00, 0x55, 0x4b, 0x05, 0x4f,
	0xb5, 0x6a, 0xa4, 0x55, 0x0f, 0xb1, 0x7d, 0x29, 0x3f, 0x74, 0x65, 0xc3, 0xba, 0x78, 0x5c, 0x0d,
	0x21, 0x7a, 0x0e, 0x13, 0xbb, 0x9d, 0xa4, 0x24, 0x07, 0x16, 0xfa, 0xda, 0x77, 0x60, 0x73, 0xdf,
	0xc9, 0x81, 0x2d, 0x7e, 0x3b, 0x70, 0x7c, 0xcb, 0x25, 0x42, 0x70, 0xa4, 0xc9, 0xe6, 0xd6, 0x75,
	0x8c, 0xa6, 0xe0, 0xf2, 0xcc, 0x8e, 0xed, 0xf2, 0xec, 0x8e, 0x15, 0xef, 0x3f, 0xac, 0x6c, 0x60,
	0x5a, 0x90, 0xa6, 0x48, 0x88, 0xc8, 0x65, 0xcd, 0x55, 0x71, 0xd0, 0x63, 0x4f, 0x57, 0x2f, 0xb0,
	0x79, 0xb4, 0x9f, 0x78, 0xce, 0x15, 0x11, 0xa2, 0xdb, 0xf2, 0xbc, 0x64, 0x19, 0x5e, 0x93, 0xa6,
	0xb8, 0x18, 0xb8, 0xf1, 0x71, 0x71, 0x13, 0x52, 0x5f, 0xdf, 0xd1, 0xd9, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x8b, 0x0a, 0x13, 0xfe, 0x68, 0x03, 0x00, 0x00,
}
