Logs: 
  - HashStrategy: default
  - LogID: testlog
  - Origin: origin string (first line of checkpoint)
  - PubKey: testlog+b69ecd61+AXCbEtyrQUhoUcMV/fZz905iDDoe7UAq3X0oD5ZUVyMS
  - UseCompact: false
