# action.yml
name: 'Witness PR validator'
description: 'Serverless log: Witness PR validator'
inputs:
  log_dir:
    description: 'Location of the log files in the repo'
    required: true
    default: '.'
  witness_key_files:
    description: 'Path glob within the pristine repo matching known witness keys'
    required: true
  log_public_key:
    description: 'Log public key string (in note format)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'loader'
  color: 'orange'
