// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.proto

package log

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	trillian "github.com/google/trillian"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InternalMessage has the details of a message that is going to
// be sent under the corporate account. It contains details that
// wouldn't be sent to the Tritter service, such as username of
// the user that made the request.
type InternalMessage struct {
	User                 string               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InternalMessage) Reset()         { *m = InternalMessage{} }
func (m *InternalMessage) String() string { return proto.CompactTextString(m) }
func (*InternalMessage) ProtoMessage()    {}
func (*InternalMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{0}
}

func (m *InternalMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalMessage.Unmarshal(m, b)
}
func (m *InternalMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalMessage.Marshal(b, m, deterministic)
}
func (m *InternalMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalMessage.Merge(m, src)
}
func (m *InternalMessage) XXX_Size() int {
	return xxx_messageInfo_InternalMessage.Size(m)
}
func (m *InternalMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InternalMessage proto.InternalMessageInfo

func (m *InternalMessage) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *InternalMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *InternalMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type LogProof struct {
	Root                 *trillian.SignedLogRoot `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Proof                *trillian.Proof         `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LogProof) Reset()         { *m = LogProof{} }
func (m *LogProof) String() string { return proto.CompactTextString(m) }
func (*LogProof) ProtoMessage()    {}
func (*LogProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{1}
}

func (m *LogProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogProof.Unmarshal(m, b)
}
func (m *LogProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogProof.Marshal(b, m, deterministic)
}
func (m *LogProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogProof.Merge(m, src)
}
func (m *LogProof) XXX_Size() int {
	return xxx_messageInfo_LogProof.Size(m)
}
func (m *LogProof) XXX_DiscardUnknown() {
	xxx_messageInfo_LogProof.DiscardUnknown(m)
}

var xxx_messageInfo_LogProof proto.InternalMessageInfo

func (m *LogProof) GetRoot() *trillian.SignedLogRoot {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *LogProof) GetProof() *trillian.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type LogRequest struct {
	Message              *InternalMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{2}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetMessage() *InternalMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type LogResponse struct {
	Proof                *LogProof `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{3}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetProof() *LogProof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type LatestRootRequest struct {
	LastTreeSize         int64    `protobuf:"varint,1,opt,name=last_tree_size,json=lastTreeSize,proto3" json:"last_tree_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatestRootRequest) Reset()         { *m = LatestRootRequest{} }
func (m *LatestRootRequest) String() string { return proto.CompactTextString(m) }
func (*LatestRootRequest) ProtoMessage()    {}
func (*LatestRootRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{4}
}

func (m *LatestRootRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestRootRequest.Unmarshal(m, b)
}
func (m *LatestRootRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestRootRequest.Marshal(b, m, deterministic)
}
func (m *LatestRootRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestRootRequest.Merge(m, src)
}
func (m *LatestRootRequest) XXX_Size() int {
	return xxx_messageInfo_LatestRootRequest.Size(m)
}
func (m *LatestRootRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestRootRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LatestRootRequest proto.InternalMessageInfo

func (m *LatestRootRequest) GetLastTreeSize() int64 {
	if m != nil {
		return m.LastTreeSize
	}
	return 0
}

type LatestRootResponse struct {
	Root                 *trillian.SignedLogRoot `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Proof                *trillian.Proof         `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LatestRootResponse) Reset()         { *m = LatestRootResponse{} }
func (m *LatestRootResponse) String() string { return proto.CompactTextString(m) }
func (*LatestRootResponse) ProtoMessage()    {}
func (*LatestRootResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{5}
}

func (m *LatestRootResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatestRootResponse.Unmarshal(m, b)
}
func (m *LatestRootResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatestRootResponse.Marshal(b, m, deterministic)
}
func (m *LatestRootResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatestRootResponse.Merge(m, src)
}
func (m *LatestRootResponse) XXX_Size() int {
	return xxx_messageInfo_LatestRootResponse.Size(m)
}
func (m *LatestRootResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LatestRootResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LatestRootResponse proto.InternalMessageInfo

func (m *LatestRootResponse) GetRoot() *trillian.SignedLogRoot {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *LatestRootResponse) GetProof() *trillian.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

type GetEntryRequest struct {
	TreeSize             int64    `protobuf:"varint,1,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	Index                int64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEntryRequest) Reset()         { *m = GetEntryRequest{} }
func (m *GetEntryRequest) String() string { return proto.CompactTextString(m) }
func (*GetEntryRequest) ProtoMessage()    {}
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{6}
}

func (m *GetEntryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntryRequest.Unmarshal(m, b)
}
func (m *GetEntryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntryRequest.Marshal(b, m, deterministic)
}
func (m *GetEntryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntryRequest.Merge(m, src)
}
func (m *GetEntryRequest) XXX_Size() int {
	return xxx_messageInfo_GetEntryRequest.Size(m)
}
func (m *GetEntryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntryRequest proto.InternalMessageInfo

func (m *GetEntryRequest) GetTreeSize() int64 {
	if m != nil {
		return m.TreeSize
	}
	return 0
}

func (m *GetEntryRequest) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

type GetEntryResponse struct {
	Data                 []byte          `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Proof                *trillian.Proof `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetEntryResponse) Reset()         { *m = GetEntryResponse{} }
func (m *GetEntryResponse) String() string { return proto.CompactTextString(m) }
func (*GetEntryResponse) ProtoMessage()    {}
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a153da538f858886, []int{7}
}

func (m *GetEntryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEntryResponse.Unmarshal(m, b)
}
func (m *GetEntryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEntryResponse.Marshal(b, m, deterministic)
}
func (m *GetEntryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEntryResponse.Merge(m, src)
}
func (m *GetEntryResponse) XXX_Size() int {
	return xxx_messageInfo_GetEntryResponse.Size(m)
}
func (m *GetEntryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEntryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetEntryResponse proto.InternalMessageInfo

func (m *GetEntryResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetEntryResponse) GetProof() *trillian.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func init() {
	proto.RegisterType((*InternalMessage)(nil), "log.InternalMessage")
	proto.RegisterType((*LogProof)(nil), "log.LogProof")
	proto.RegisterType((*LogRequest)(nil), "log.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "log.LogResponse")
	proto.RegisterType((*LatestRootRequest)(nil), "log.LatestRootRequest")
	proto.RegisterType((*LatestRootResponse)(nil), "log.LatestRootResponse")
	proto.RegisterType((*GetEntryRequest)(nil), "log.GetEntryRequest")
	proto.RegisterType((*GetEntryResponse)(nil), "log.GetEntryResponse")
}

func init() { proto.RegisterFile("log.proto", fileDescriptor_a153da538f858886) }

var fileDescriptor_a153da538f858886 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x5f, 0x6b, 0xd4, 0x40,
	0x10, 0xf7, 0xbc, 0x6b, 0xbd, 0x9b, 0xab, 0xbd, 0xba, 0xd4, 0xf6, 0x88, 0x0f, 0x96, 0xa8, 0x50,
	0xaa, 0x24, 0x10, 0x5f, 0x2c, 0x08, 0x82, 0x28, 0x22, 0xa4, 0x20, 0x69, 0x9f, 0x7c, 0xf0, 0xc8,
	0xf5, 0xa6, 0x7b, 0x0b, 0x49, 0x26, 0xee, 0x4e, 0xc0, 0xf6, 0x53, 0xf9, 0x11, 0xe5, 0x76, 0xb3,
	0x17, 0x89, 0x2f, 0xbe, 0xf4, 0x29, 0x3b, 0xbf, 0x9d, 0xdf, 0x9f, 0x99, 0x24, 0x30, 0x29, 0x48,
	0x46, 0xb5, 0x26, 0x26, 0x31, 0x2c, 0x48, 0x06, 0xfb, 0xac, 0x55, 0x51, 0xa8, 0xbc, 0x72, 0x60,
	0x70, 0xe4, 0xeb, 0x45, 0x41, 0x72, 0x91, 0xd7, 0xaa, 0xc5, 0x9f, 0x4b, 0x22, 0x59, 0x60, 0x6c,
	0xab, 0x65, 0x73, 0x13, 0xb3, 0x2a, 0xd1, 0x70, 0x5e, 0xd6, 0xae, 0x21, 0xbc, 0x85, 0xd9, 0xd7,
	0x8a, 0x51, 0x57, 0x79, 0x71, 0x81, 0xc6, 0xe4, 0x12, 0x85, 0x80, 0x51, 0x63, 0x50, 0xcf, 0x07,
	0x27, 0x83, 0xd3, 0x49, 0x66, 0xcf, 0x62, 0x0e, 0x8f, 0x4a, 0x77, 0x3d, 0x7f, 0x68, 0x61, 0x5f,
	0x8a, 0x77, 0x30, 0xd9, 0x6a, 0xce, 0x87, 0x27, 0x83, 0xd3, 0x69, 0x12, 0x44, 0xce, 0x35, 0xf2,
	0xae, 0xd1, 0x95, 0xef, 0xc8, 0xba, 0xe6, 0xf0, 0x07, 0x8c, 0x53, 0x92, 0xdf, 0x34, 0xd1, 0x8d,
	0x78, 0x0d, 0x23, 0x4d, 0xc4, 0xd6, 0x73, 0x9a, 0x1c, 0x47, 0xdb, 0xf1, 0x2e, 0x95, 0xac, 0x70,
	0x95, 0x92, 0xcc, 0x88, 0x38, 0xb3, 0x4d, 0xe2, 0x15, 0xec, 0xd4, 0x1b, 0x96, 0x8d, 0x32, 0x4d,
	0x66, 0x5d, 0xb7, 0x15, 0xcb, 0xdc, 0x6d, 0xf8, 0x1e, 0x60, 0xc3, 0xc3, 0x9f, 0x0d, 0x1a, 0x16,
	0x51, 0x37, 0x81, 0x33, 0x39, 0x8c, 0x36, 0x3b, 0xed, 0x0d, 0xbf, 0x9d, 0x2b, 0x4c, 0x60, 0x6a,
	0xd9, 0xa6, 0xa6, 0xca, 0xa0, 0x78, 0xe1, 0x3d, 0x1d, 0xf9, 0xb1, 0x25, 0xfb, 0xf8, 0xde, 0xf1,
	0x1c, 0x9e, 0xa4, 0x39, 0xa3, 0x61, 0x1b, 0xb6, 0x35, 0x7e, 0x09, 0xfb, 0x45, 0x6e, 0x78, 0xc1,
	0x1a, 0x71, 0x61, 0xd4, 0x9d, 0xf3, 0x1f, 0x66, 0x7b, 0x1b, 0xf4, 0x4a, 0x23, 0x5e, 0xaa, 0x3b,
	0x0c, 0xd7, 0x20, 0xfe, 0xa6, 0xb6, 0xae, 0xf7, 0xb1, 0x96, 0x4f, 0x30, 0xfb, 0x82, 0xfc, 0xb9,
	0x62, 0x7d, 0xeb, 0x23, 0x3e, 0x83, 0x49, 0x3f, 0xdd, 0x98, 0xdb, 0x64, 0xe2, 0x10, 0x76, 0x54,
	0xb5, 0xc2, 0x5f, 0x56, 0x76, 0x98, 0xb9, 0x22, 0xbc, 0x80, 0x83, 0x4e, 0xa5, 0x4d, 0x2b, 0x60,
	0xb4, 0xca, 0x39, 0xb7, 0x0a, 0x7b, 0x99, 0x3d, 0xff, 0x67, 0xa8, 0xe4, 0xf7, 0x00, 0x76, 0x53,
	0x92, 0x12, 0xb5, 0x38, 0x83, 0x61, 0x4a, 0x52, 0xcc, 0xfc, 0x86, 0xdb, 0x90, 0xc1, 0x41, 0x07,
	0x38, 0xbf, 0xf0, 0x81, 0xf8, 0x00, 0xd0, 0x6d, 0x4d, 0x1c, 0xb9, 0x8e, 0xfe, 0x1b, 0x08, 0x8e,
	0xff, 0xc1, 0xb7, 0x02, 0xe7, 0x30, 0xf6, 0x63, 0x08, 0xf7, 0x41, 0xf4, 0x76, 0x13, 0x3c, 0xed,
	0xa1, 0x9e, 0xfa, 0xf1, 0xcd, 0xf7, 0x33, 0xa9, 0x78, 0xdd, 0x2c, 0xa3, 0x6b, 0x2a, 0xe3, 0x72,
	0xdd, 0xf0, 0xf5, 0x5a, 0x55, 0x86, 0xaa, 0x98, 0xb5, 0x62, 0x46, 0x6d, 0x9f, 0x4b, 0xe2, 0xb8,
	0x20, 0xb9, 0xdc, 0xb5, 0xff, 0xc2, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x04, 0xa8,
	0xdb, 0xc9, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggerClient is the client API for Logger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggerClient interface {
	// Log the message and return a proof of inclusion.
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	// Get the latest log root and consistency proof from specified version.
	LatestRoot(ctx context.Context, in *LatestRootRequest, opts ...grpc.CallOption) (*LatestRootResponse, error)
	GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error)
}

type loggerClient struct {
	cc *grpc.ClientConn
}

func NewLoggerClient(cc *grpc.ClientConn) LoggerClient {
	return &loggerClient{cc}
}

func (c *loggerClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/log.Logger/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) LatestRoot(ctx context.Context, in *LatestRootRequest, opts ...grpc.CallOption) (*LatestRootResponse, error) {
	out := new(LatestRootResponse)
	err := c.cc.Invoke(ctx, "/log.Logger/LatestRoot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggerClient) GetEntry(ctx context.Context, in *GetEntryRequest, opts ...grpc.CallOption) (*GetEntryResponse, error) {
	out := new(GetEntryResponse)
	err := c.cc.Invoke(ctx, "/log.Logger/GetEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggerServer is the server API for Logger service.
type LoggerServer interface {
	// Log the message and return a proof of inclusion.
	Log(context.Context, *LogRequest) (*LogResponse, error)
	// Get the latest log root and consistency proof from specified version.
	LatestRoot(context.Context, *LatestRootRequest) (*LatestRootResponse, error)
	GetEntry(context.Context, *GetEntryRequest) (*GetEntryResponse, error)
}

// UnimplementedLoggerServer can be embedded to have forward compatible implementations.
type UnimplementedLoggerServer struct {
}

func (*UnimplementedLoggerServer) Log(ctx context.Context, req *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (*UnimplementedLoggerServer) LatestRoot(ctx context.Context, req *LatestRootRequest) (*LatestRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LatestRoot not implemented")
}
func (*UnimplementedLoggerServer) GetEntry(ctx context.Context, req *GetEntryRequest) (*GetEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEntry not implemented")
}

func RegisterLoggerServer(s *grpc.Server, srv LoggerServer) {
	s.RegisterService(&_Logger_serviceDesc, srv)
}

func _Logger_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Logger/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_LatestRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).LatestRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Logger/LatestRoot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).LatestRoot(ctx, req.(*LatestRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Logger_GetEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggerServer).GetEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/log.Logger/GetEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggerServer).GetEntry(ctx, req.(*GetEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Logger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "log.Logger",
	HandlerType: (*LoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _Logger_Log_Handler,
		},
		{
			MethodName: "LatestRoot",
			Handler:    _Logger_LatestRoot_Handler,
		},
		{
			MethodName: "GetEntry",
			Handler:    _Logger_GetEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
